package pl.blackwater.core.enums;

public enum ChatControlType {

    CASEOPEN,DEATH,KILLKEY,KILLDIAMOND,KILLTURBO,KILLKILLSTREAK,KILLMONEYLEVEL,ITEMSHOP,KILLSTREAKGLOBAL,AUTOMESSAGE,MARKETGLOBAL,HEADHUNTER;
}
